baseurl = "https://ianmccarthyecon.netlify.app/"
title = "Ian McCarthy"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "ianmccarthy"
googleAnalytics = "UA-158371232-1"
enableEmoji = true

[params]
    author = "Ian McCarthy"
    description = "Personal website for Ian McCarthy"
    keywords = "research, personal"
    info1 = "Associate Professor of Economics, Emory University"
    info2 = "Faculty Research Fellow, NBER"    
    avatarurl = "images/mccarthy-headshot.jpg"
    footercontent = ""

    dateformat = "May 26, 2020"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
#    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5
    
    # Custom CSS
    custom_css = ["css/academicons.min.css"]

    # Custom JS
    custom_js = ["customs/js_style.js"]
    

[taxonomies]
  series = "series"

[[params.social]]
    name = "CV"
    icon = "ai ai-cv"
    weight = 1
    url = "files/mccarthy_cv.pdf"
[[params.social]]
    name = "google-scholar"
    icon = "ai ai-google-scholar"
    weight = 2
    url = "https://scholar.google.com/citations?user=zRCE7V0AAAAJ&hl=en"
[[params.social]]
    name = "RePec"
    icon = "ai ai-ideas-repec"
    weight = 3
    url = "https://ideas.repec.org/f/pmc207.html"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 4
    url = "https://github.com/imccart/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 5
    url = "https://twitter.com/ianhealthecon/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 6
    url = "https://www.linkedin.com/in/ianmmccarthy/"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "Research"
        weight = 1
        url = "/research/"

        [[languages.en.menu.main]]
        name = "Teaching"
        weight = 2
        url = "/teaching/"

        [[languages.en.menu.main]]
        name = "Resources"
        weight = 3
        url = "/resources/"

        [[languages.en.menu.main]]
        name = "Programs"
        weight = 4
        url = "/programs/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "/contact/"